services:
  - type: web
    name: controle-gestao-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: EVOLUTION_API_URL
        sync: false
      - key: EVOLUTION_API_KEY
        sync: false
      - key: EVOLUTION_INSTANCE_NAME
        sync: false
      - key: GEMINI_API_KEY
        sync: false
